#=============================================================================
# The detailed example of init.toml for SpaceVim
# Author: Gabirel ( gabrielf977q at gmail.com )
# Date: 2018-08-28
# URL: https://godeep.pro/
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "molokai"
  background = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = false
  relativenumber = false

# Layers listed in SpaceVim with command: [SPC] h l
######## Function Layers Start ########
#
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "checkers"
  enable = true
  show_cursor_error = true


## Enable cscope layer
#[[layers]]
#  name = "cscope"
#
## Enable ctrlp layer
#[[layers]]
#  name = "ctrlp"

[[layers]]
  name = "debug"
  enable = false

# Enable VersionControl layer
[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lsp"
  enable = false
  filetypes = [
    "rust",
    "javascript"
  ]
  [layers.override_cmd]
    rust = ["rustup", "run", "nightly", "rls"]

[[layers]]
  name = "leaderf"
  enable = true

[[layers]]
  name = 'shell'
  # Optional Value: {"top", "bottom", "left", "right", "full"}
  default_position = 'bottom'
  default_height = 30

[[layers]]
  name = "sudo"
  enable = true

# Layer: tags
# Requirements: 
#   - ctags
#   - python-pygments
# More details: https://spacevim.org/layers/tags/
[[layers]]
  name = "tags"
  enable = false

#
######## Function Layers End   ########


######## Language Layers Start ########
#
[[layers]]
  name = "lang#c"
  enable = true
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
  name = "lang#dockerfile"
  enable = true

[[layers]]
  name = "lang#html"
  enable = true

[[layers]]
  name = "lang#java"
  enable = false

[[layers]]
  name = "lang#javascript"
  enable = false
  auto_fix = false
  enable_flow_syntax = false

[[layers]]
  name = "lang#lua"
  enable = true

# Layer: lang#markdown
# Formatting: 
# SpaceVim use remark to formatting markdown file, so you need to install this program. you can install it via npm:
# 
#   `npm -g install remark`
#   `npm -g install remark-cli`
#   `npm -g install remark-stringify`
[[layers]]
  name = "lang#markdown"
  enable = true

# Layer: lang#python
# Opthons:
#   Syntax Checking: `pip install --user flake8`
#   Buffer formatting: `pip install --user yapf`
#   Format imports: `pip install --user autoflake`
#   Sort imports: `pip install --user isort`
[[layers]]
  name = "lang#python"
  enable = false

# Layer: lang#typescript
# Requirements:
#   - `npm install -g typescript`
[[layers]]
  name = "lang#typescript"
  enable = false

#
######## Language Layers End   ########